In [81]:
import os
import sys
sys.path.append('../../MARS')
#sys.path.append('../../MARS/preprocess_dicoms')
#sys.path.append('../../MARS/run_lars')
import ast
import pandas as pd
import numpy as np
import os
import h5py
import pydicom 
import glob
#import tkinter
#os.environ['MPLCONFIGDIR'] = os.getcwd() + "/configs/"
import matplotlib
#matplotlib.use('TkAgg')
#matplotlib.use('qtagg') 
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import ImageGrid
#import itertools
import pickle
import scipy
import pdb
import time
import argparse
from collections import Counter
from MARS.preprocess_dicoms.read_dicom_functions import GetDicomSlices, GetImageFromDicomSlices, GetImageFromDicomSlices_PixelData, ImageBQML2SUV

In [4]:
log_files = glob.glob("/gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_*_*.log")   # adjust path if logs are in a subfolder

for op in log_files:
    with open(op, "r") as infile:
        # print the total number of lines in infile
        print(f"Total lines in {op}: {sum(1 for line in infile)}")

Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6178131_45.log: 967
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6173745_49.log: 1029
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6177992_30.log: 1090
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6178133_47.log: 867
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6177995_33.log: 1500
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6176266_3.log: 1086
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6177993_31.log: 1150
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6176849_5.log: 1251
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6177998_36.log: 1117
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6176850_6.log: 1330
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6177876_21.log: 1189
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6176852_8.log: 1030
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6177310_15.log: 1409
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6176848_4.log: 1324
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6178001_39.log: 1376
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6177999_37.log: 1049
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6178003_41.log: 1136
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6177985_23.log: 1255
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6177984_22.log: 1134
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6173752_1.log: 888
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6177988_26.log: 1497
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6177986_24.log: 1037
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6177299_12.log: 1478
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6176855_11.log: 867
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6177989_27.log: 1633
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6177437_16.log: 1093
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6178134_48.log: 937
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6178002_40.log: 1281
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6177994_32.log: 1062
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6176854_10.log: 1061
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6178132_46.log: 1125
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6173746_0.log: 1163
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6178062_44.log: 1069
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6173753_2.log: 1050
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6177875_20.log: 1147
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6176851_7.log: 882
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6178035_43.log: 1060
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6177438_17.log: 1490
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6177300_13.log: 1371
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6177987_25.log: 821
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6178007_42.log: 984
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6177301_14.log: 1096
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6177440_19.log: 951
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6177990_28.log: 1063
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6176853_9.log: 1129
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6177996_34.log: 1018
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6177439_18.log: 845
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6177997_35.log: 1343
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6177991_29.log: 854
Total lines in /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/log_for_6178000_38.log: 1473

In [12]:


output_file = "/gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/merged_logs.log"

with open(output_file, "w") as outfile:
    for fname in log_files:
        with open(fname, "r") as infile:
            # Write filename as a header (optional)
            outfile.write(f"===== {fname} =====\n")
            outfile.write(infile.read())
            outfile.write("\n\n")  # spacer between logs

print(f"Merged {len(log_files)} logs into {output_file}")

Merged 50 logs into /gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/merged_logs.log

In [5]:
listo = glob.glob('/gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/datafiles/data_scan_*_0.csv')
list_df = []

for x in listo:
    dfo = pd.read_csv(x)
    list_df.append(dfo)

In [4]:
zz = pd.read_csv('/gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/datafiles/data_count_axial_pixel_size.csv')

/tmp/ipykernel_304775/678610853.py:1: DtypeWarning: Columns (59) have mixed types. Specify dtype option on import or set low_memory=False.
  zz = pd.read_csv('/gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/datafiles/data_count_axial_pixel_size.csv')

In [47]:
comb = pd.read_csv('/gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/datafiles/data_scan_curated.csv')
#comb['fullfile'] = comb['filepath'].astype(str) + comb['fullfile']

In [49]:
comb_all = pd.read_csv('/gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/datafiles/data_scan.csv')
comb_cur = pd.read_csv('/gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/datafiles/data_scan_curated.csv')

des_all = pd.read_csv('/gpfs/data/mayerhoeferlab/projects/myeloma/datafiles_for_mars/data_scan.csv')
des_cur = pd.read_csv('/gpfs/data/mayerhoeferlab/projects/myeloma/datafiles_for_mars/data_scan_curated.csv')

/tmp/ipykernel_400450/3800651476.py:1: DtypeWarning: Columns (59) have mixed types. Specify dtype option on import or set low_memory=False.
  comb_all = pd.read_csv('/gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/datafiles/data_scan.csv')
/tmp/ipykernel_400450/3800651476.py:4: DtypeWarning: Columns (59) have mixed types. Specify dtype option on import or set low_memory=False.
  des_all = pd.read_csv('/gpfs/data/mayerhoeferlab/projects/myeloma/datafiles_for_mars/data_scan.csv')

In [50]:
comb_all[comb_all['filepath'] == 12194426]

,filepath,filename,filename_header,fullfile,patient_id,patient_age,patient_sex,patient_weight,smoking_status,accession,...,reconstruction,corrections,pixel_unit,frame_duration,tracer,tracer_injection_time,tracer_dose,tracer_halflife,image_filter,contrast_route
1319,12194426,12194426_ct_1.h5,12194426_ct_1.pkl,/12194426_ct_1.h5,1597595,074Y,M,76.203528,NaN,12194426,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1320,12194426,12194426_pt_1.h5,12194426_pt_1.pkl,/12194426_pt_1.h5,1597595,074Y,M,76.203528,NaN,12194426,...,OSEM2D 1i21s,NORM|DTIM|RADL|DECY,PROPCPS,150000.0,FDG,123200.0,5.764600e+08,6586.2,NaN,NaN
1321,12194426,12194426_ct_2.h5,12194426_ct_2.pkl,/12194426_ct_2.h5,1597595,074Y,M,76.203528,NaN,12194426,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1322,12194426,12194426_pt_0.h5,12194426_pt_0.pkl,/12194426_pt_0.h5,1597595,074Y,M,76.203528,NaN,12194426,...,OSEM2D 2i21s,NORM|DTIM|ATTN|SCAT|RADL|DECY,BQML,150000.0,FDG,123200.0,5.764600e+08,6586.2,NaN,NaN
1323,12194426,12194426_ct_0.h5,12194426_ct_0.pkl,/12194426_ct_0.h5,1597595,074Y,M,76.203528,NaN,12194426,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
des.columns

0             PET WB Corrected
1                 WB_PET AC 3D
2             PET WB Corrected
3             PET WB Corrected
4             PET WB Corrected
                 ...
1514          PET WB Corrected
1515          PET WB Corrected
1516    PET WB _Corrected (AC)
1517        PET VERTEX TO TOES
1518          PET WB Corrected
Name: description_series, Length: 1519, dtype: object

In [82]:
patho = '/gpfs/data/mayerhoeferlab/projects/myeloma/dicom/39708174'
xyz = GetDicomSlices(patho)

In [91]:
ur = [u.SeriesDescription for u in xyz]
ur_m = [u.Modality for u in xyz]

In [92]:
ur_m

['PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'PT',
 'CT',
 'PT',
 'PT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'PT',
 'PT',
 'PT',
 'CT',
 'CT',
 'CT',
 ...]

In [ ]:
zr = pd.read_pickle('/gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/headers_pkl/39708174/39708174_pt_0.pkl')
for x in zr:
    print(x.SeriesDescription)

In [71]:
#comb_all[comb_all.filepath == 39708174][['filename', 'description_series']]
des_all[des_all.filepath == 39708174][['filename', 'description_series']]

               filename description_series
17864  39708174_pt_3.h5        Reformatted
17865  39708174_pt_4.h5        Reformatted
17866  39708174_pt_1.h5      WB_PET NAC 3D
17867  39708174_ct_0.h5    CTAC 3.75 thick
17868  39708174_pt_0.h5       WB_PET AC 3D
17869  39708174_pt_2.h5        Reformatted

In [62]:
comb[comb.filepath == 39708174].description_series

1097    WB_PET AC 3D
Name: description_series, dtype: object

In [51]:
def row_diff(dfA, dfB, colname = 'filename'):
    # get values that are in dfA but not dfB
    ret = set(dfA[colname].values) - set(dfB[colname].values)
    print(len(ret))
    return ret
row_diff(comb_all, des_all)
row_diff(comb_cur, des_cur)

row_diff(des_all, comb_all)
row_diff(des_cur, comb_cur)

800
51
0
7

{'12194426_pt_0.h5',
 '30273728_pt_0.h5',
 '38797362_pt_1.h5',
 '39708174_pt_0.h5',
 '40026035_pt_0.h5',
 '41997412_pt_0.h5',
 '6510655_pt_0.h5'}

In [ ]:
asdf = pd.read_csv('/gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/tmp.csv')
for i in range(asdf.shape[0]):
    xx = np.array(ast.literal_eval(asdf['image_orientation'].values[i]))
    crossed = np.cross(xx[:3], xx[3:])
    if not np.all(crossed == np.array([0, 0, 1])):
        print(i)
        print(np.round(crossed, 2))
        print('==')

In [55]:
des[des['imaging_plane'] == 'coronal']

,filepath,filename,filename_header,fullfile,patient_id,patient_age,patient_sex,patient_weight,accession,study_uid,...,img_mean_nonzeros,img_std_nonzeros,img_sum_nonzeros,convolution_kernel,image_filter,xray_tube_current,kvp,image_comments,smoking_status,contrast_route
5,2938443,2938443_pt_2.h5,2938443_pt_2.pkl,2938443/2938443_pt_2.h5,7287510,079Y,F,46.308000,2938443,1.3.12.2.1107.5.1.4.44843.30000005072920385017...,...,0.996660,0.993341,1.580680e+06,X-Y-Z Gaussian FWHM=5.00,NaN,NaN,NaN,NaN,NaN,NaN
36,4026061,4026061_pt_2.h5,4026061_pt_2.pkl,4026061/4026061_pt_2.h5,1629898,058Y,F,65.830000,4026061,1.2.840.113696.323972.500.62352.2007111410553,...,0.818885,0.886471,3.590883e+06,X-Y-Z Gaussian FWHM=5.00,NaN,NaN,NaN,NaN,NO,NaN
865,6158063,6158063_ct_0.h5,6158063_ct_0.pkl,6158063/6158063_ct_0.h5,2132971,061Y,F,86.260000,6158063,1.3.12.2.1107.5.1.4.48416.4.0.1430976512481679,...,4.932646,55.323428,1.348684e+06,T20s,NaN,50.0,120.0,NaN,NaN,NaN
1007,6340889,6340889_pt_3.h5,6340889_pt_3.pkl,6340889/6340889_pt_3.h5,1838443,062Y,M,81.646637,6340889,1.2.840.113696.323972.500.2332113.20111216114056,...,0.948266,1.043459,6.269947e+05,XYZ Gauss3.00,NaN,NaN,NaN,AC CT WB,UNKNOWN,NaN
1069,6409349,6409349_pt_3.h5,6409349_pt_3.pkl,6409349/6409349_pt_3.h5,1494896,075Y,F,80.285860,6409349,1.2.840.113696.323972.500.2399179.20120113112336,...,0.907374,1.401781,6.432403e+05,XYZ Gauss3.00,NaN,NaN,NaN,AC CT WB,UNKNOWN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19384,43486598,43486598_pt_2.h5,43486598_pt_2.pkl,43486598/43486598_pt_2.h5,16765894,055Y,M,95.255000,43486598,1.2.840.114350.2.232.2.798268.2.880366082.1,...,0.815434,1.186641,7.663502e+05,XYZ Gauss5.00,NaN,NaN,NaN,AC CT WB EFOV iMAR,UNKNOWN,NaN
19408,43608032,43608032_ct_4.h5,43608032_ct_4.pkl,43608032/43608032_ct_4.h5,12734299,061Y,M,100.699000,43608032,1.2.840.114350.2.232.2.798268.2.875513226.1,...,-275.117529,419.174127,-8.443480e+09,"['Br38f', '3']",NaN,211.0,120.0,NaN,UNKNOWN,NaN
19409,43608032,43608032_pt_2.h5,43608032_pt_2.pkl,43608032/43608032_pt_2.h5,12734299,061Y,M,100.699000,43608032,1.2.840.114350.2.232.2.798268.2.875513226.1,...,0.857930,2.501895,8.680667e+05,XYZ Gauss5.00,NaN,NaN,NaN,AC CT WB EFOV iMAR,UNKNOWN,NaN
19411,43644283,43644283_pt_3.h5,43644283_pt_3.pkl,43644283/43644283_pt_3.h5,9114915,091Y,M,75.751000,43644283,1.2.840.114350.2.232.2.798268.2.883783980.1,...,0.869360,1.020701,2.035668e+06,XYZ Gauss5.00,NaN,NaN,NaN,AC CT WB 5.0 HD_FoV,UNKNOWN,NaN
19416,43644283,43644283_ct_3.h5,43644283_ct_3.pkl,43644283/43644283_ct_3.h5,9114915,091Y,M,75.751000,43644283,1.2.840.114350.2.232.2.798268.2.883783980.1,...,-288.566976,439.632838,-6.537243e+09,"['Br38f', '3']",NaN,124.0,120.0,NaN,UNKNOWN,NaN

In [57]:
for i in range(des.shape[0]):
    xx = np.array(ast.literal_eval(des['image_orientation'].values[i]))
    crossed = np.cross(xx[:3], xx[3:])
    if not np.all(crossed == np.array([0, 0, 1])):
        print(i)
        print(np.round(crossed, 2))
        print('==')

5
[-0.  1.  0.]
==
36
[-0.  1.  0.]
==
865
[-0.  1.  0.]
==
1007
[-0.  1.  0.]
==
1069
[-0.  1.  0.]
==
1082
[-0.  1.  0.]
==
1093
[-0.  1.  0.]
==
1098
[-0.  1.  0.]
==
1135
[-0.  1.  0.]
==
1157
[-0.  1.  0.]
==
1178
[-0.  1.  0.]
==
1190
[-0.  1.  0.]
==
1211
[-0.  1.  0.]
==
1231
[-0.  1.  0.]
==
1240
[-0.  1.  0.]
==
1246
[-0.  1.  0.]
==
1251
[-0.  1.  0.]
==
1260
[-0.  1.  0.]
==
1270
[-0.  1.  0.]
==
1282
[-0.  1.  0.]
==
1294
[-0.  1.  0.]
==
1302
[-0.  1.  0.]
==
1317
[-0.  1.  0.]
==
1322
[-0.  1.  0.]
==
1337
[-0.  1.  0.]
==
1350
[-0.  1.  0.]
==
1360
[-0.  1.  0.]
==
1367
[-0.  1.  0.]
==
1369
[-0.  1.  0.]
==
1381
[-0.  1.  0.]
==
1386
[-0.  1.  0.]
==
1389
[-0.  1.  0.]
==
1398
[-0.  1.  0.]
==
1409
[-0.  1.  0.]
==
1414
[-0.  1.  0.]
==
1420
[-0.  1.  0.]
==
1426
[-0.  1.  0.]
==
1436
[-0.  1.  0.]
==
1454
[-0.  1.  0.]
==
1469
[-0.  1.  0.]
==
1479
[-0.  1.  0.]
==
1482
[-0.  1.  0.]
==
1506
[-0.  1.  0.]
==
1512
[-0.  1.  0.]
==
1547
[-0.  1.  0.]
==
1571
[-0.  1.  0.]
==
1598
[-0.  1.  0.]
==
1611
[-0.  1.  0.]
==
1629
[-0.  1.  0.]
==
1649
[-0.  1.  0.]
==
1658
[-0.  1.  0.]
==
1673
[-0.  1.  0.]
==
1678
[-0.  1.  0.]
==
1686
[-0.  1.  0.]
==
1697
[-0.  1.  0.]
==
1705
[-0.  1.  0.]
==
1712
[-0.  1.  0.]
==
1726
[-0.  1.  0.]
==
1731
[-0.  1.  0.]
==
1740
[-0.  1.  0.]
==
1754
[-0.  1.  0.]
==
1770
[-0.  1.  0.]
==
1777
[-0.  1.  0.]
==
1785
[-0.  1.  0.]
==
1799
[-0.  1.  0.]
==
1806
[-0.  1.  0.]
==
1825
[-0.  1.  0.]
==
1830
[-0.  1.  0.]
==
1841
[-0.  1.  0.]
==
1845
[-0.  1.  0.]
==
1852
[-0.  1.  0.]
==
1861
[-0.  1.  0.]
==
1865
[-0.  1.  0.]
==
1877
[-0.  1.  0.]
==
1886
[-0.  1.  0.]
==
1896
[-0.  1.  0.]
==
1901
[-0.  1.  0.]
==
1909
[-0.  1.  0.]
==
1926
[-0.  1.  0.]
==
1941
[-0.  1.  0.]
==
1949
[-0.  1.  0.]
==
1978
[-0.  1.  0.]
==
1985
[-0.  1.  0.]
==
2007
[-0.  1.  0.]
==
2014
[-0.  1.  0.]
==
2024
[-0.  1.  0.]
==
2028
[-0.  1.  0.]
==
2044
[-0.  1.  0.]
==
2056
[-0.  1.  0.]
==
2065
[-0.  1.  0.]
==
2069
[-0.  1.  0.]
==
2070
[-0.  1.  0.]
==
2082
[-0.  1.  0.]
==
2087
[-0.  1.  0.]
==
2094
[-0.  1.  0.]
==
2104
[-0.  1.  0.]
==
2112
[-0.  1.  0.]
==
2116
[-0.  1.  0.]
==
2124
[-0.  1.  0.]
==
2126
[-0.  1.  0.]
==
2134
[-0.  1.  0.]
==
2142
[-0.  1.  0.]
==
2151
[-0.  1.  0.]
==
2153
[-0.  1.  0.]
==
2163
[-0.  1.  0.]
==
2166
[-0.  1.  0.]
==
2178
[-0.  1.  0.]
==
2179
[-0.  1.  0.]
==
2187
[-0.  1.  0.]
==
2193
[-0.  1.  0.]
==
2198
[-0.  1.  0.]
==
2202
[-0.  1.  0.]
==
2206
[-0.  1.  0.]
==
2210
[-0.  1.  0.]
==
2221
[-0.  1.  0.]
==
2235
[-0.  1.  0.]
==
2240
[-0.  1.  0.]
==
2242
[-0.  1.  0.]
==
2249
[-0.  1.  0.]
==
2252
[-0.  1.  0.]
==
2261
[-0.  1.  0.]
==
2267
[-0.  1.  0.]
==
2275
[-0.  1.  0.]
==
2288
[-0.  1.  0.]
==
2307
[-0.  1.  0.]
==
2312
[-0.  1.  0.]
==
2326
[-0.  1.  0.]
==
2345
[-0.  1.  0.]
==
2348
[-0.  1.  0.]
==
2358
[-0.  1.  0.]
==
2363
[-0.  1.  0.]
==
2376
[-0.  1.  0.]
==
2383
[-0.  1.  0.]
==
2401
[-0.  1.  0.]
==
2414
[-0.  1.  0.]
==
2437
[-0.  1.  0.]
==
2454
[-0.  1.  0.]
==
2464
[-0.  1.  0.]
==
2466
[-0.  1.  0.]
==
2473
[-0.  1.  0.]
==
2479
[-0.  1.  0.]
==
2490
[-0.  1.  0.]
==
2501
[-0.  1.  0.]
==
2509
[-0.  1.  0.]
==
2510
[-0.  1.  0.]
==
2517
[-0.  1.  0.]
==
2529
[-0.  1.  0.]
==
2536
[-0.  1.  0.]
==
2548
[-0.  1.  0.]
==
2554
[-0.  1.  0.]
==
2561
[-0.  1.  0.]
==
2572
[-0.  1.  0.]
==
2575
[-0.  1.  0.]
==
2595
[-0.  1.  0.]
==
2607
[-0.  1.  0.]
==
2617
[-0.  1.  0.]
==
2628
[-0.  1.  0.]
==
2635
[-0.  1.  0.]
==
2639
[-0.  1.  0.]
==
2645
[-0.  1.  0.]
==
2650
[-0.  1.  0.]
==
2660
[-0.  1.  0.]
==
2665
[-0.  1.  0.]
==
2675
[-0.  1.  0.]
==
2682
[-0.  1.  0.]
==
2694
[-0.  1.  0.]
==
2706
[-0.  1.  0.]
==
2714
[-0.  1.  0.]
==
2719
[-0.  1.  0.]
==
2728
[-0.  1.  0.]
==
2730
[-0.  1.  0.]
==
2749
[-0.  1.  0.]
==
2753
[-0.  1.  0.]
==
2754
[-0.  1.  0.]
==
2764
[-0.  1.  0.]
==
2770
[-0.  1.  0.]
==
2771
[-0.  1.  0.]
==
2780
[-0.  1.  0.]
==
2793
[-0.  1.  0.]
==
2794
[-0.  1.  0.]
==
2820
[-0.  1.  0.]
==
2827
[-0.  1.  0.]
==
2848
[-0.  1.  0.]
==
2864
[-0.  1.  0.]
==
2873
[-0.  1.  0.]
==
2877
[-0.  1.  0.]
==
2883
[-0.  1.  0.]
==
2907
[-0.  1.  0.]
==
2917
[-0.  1.  0.]
==
2921
[-0.  1.  0.]
==
2930
[-0.  1.  0.]
==
2934
[-0.  1.  0.]
==
2943
[-0.  1.  0.]
==
2949
[-0.  1.  0.]
==
2951
[-0.  1.  0.]
==
2969
[-0.  1.  0.]
==
2978
[-0.  1.  0.]
==
3002
[-0.  1.  0.]
==
3012
[-0.  1.  0.]
==
3025
[-0.  1.  0.]
==
3061
[-0.  1.  0.]
==
3073
[-0.  1.  0.]
==
3084
[-0.  1.  0.]
==
3106
[-0.  1.  0.]
==
3116
[-0.  1.  0.]
==
3120
[-0.  1.  0.]
==
3131
[-0.  1.  0.]
==
3137
[-0.  1.  0.]
==
3146
[-0.  1.  0.]
==
3168
[-0.  1.  0.]
==
3172
[-0.  1.  0.]
==
3173
[-0.  1.  0.]
==
3186
[-0.  1.  0.]
==
3192
[-0.  1.  0.]
==
3202
[-0.  1.  0.]
==
3214
[-0.  1.  0.]
==
3216
[-0.  1.  0.]
==
3224
[-0.  1.  0.]
==
3241
[-0.  1.  0.]
==
3246
[-0.  1.  0.]
==
3251
[-0.  1.  0.]
==
3267
[-0.  1.  0.]
==
3282
[-0.  1.  0.]
==
3296
[-0.  1.  0.]
==
3302
[-0.  1.  0.]
==
3312
[-0.  1.  0.]
==
3322
[-0.  1.  0.]
==
3338
[-0.  1.  0.]
==
3350
[-0.  1.  0.]
==
3362
[-0.  1.  0.]
==
3367
[-0.  1.  0.]
==
3378
[-0.  1.  0.]
==
3389
[-0.  1.  0.]
==
3401
[-0.  1.  0.]
==
3407
[-0.  1.  0.]
==
3418
[-0.  1.  0.]
==
3427
[-0.  1.  0.]
==
3431
[-0.  1.  0.]
==
3446
[-0.  1.  0.]
==
3448
[-1  0  0]
==
3451
[0 1 0]
==
3459
[-0.  1.  0.]
==
3466
[-0.  1.  0.]
==
3481
[-0.  1.  0.]
==
3490
[0 1 0]
==
3493
[-1  0  0]
==
3497
[-1  0  0]
==
3498
[0 1 0]
==
3515
[-0.  1.  0.]
==
3528
[-0.  1.  0.]
==
3537
[-0.  1.  0.]
==
3543
[-0.  1.  0.]
==
3555
[-0.  1.  0.]
==
3561
[-0.  1.  0.]
==
3572
[-0.  1.  0.]
==
3580
[-0.  1.  0.]
==
3588
[-0.  1.  0.]
==
3591
[-0.  1.  0.]
==
3596
[-0.  1.  0.]
==
3616
[-0.  1.  0.]
==
3626
[-0.  1.  0.]
==
3643
[-0.  1.  0.]
==
3660
[-1  0  0]
==
3662
[0 1 0]
==
3665
[-0.  1.  0.]
==
3691
[-0.  1.  0.]
==
3699
[-0.  1.  0.]
==
3707
[-0.  1.  0.]
==
3711
[-0.  1.  0.]
==
3718
[-0.  1.  0.]
==
3729
[-1  0  0]
==
3731
[0 1 0]
==
3733
[-1  0  0]
==
3742
[-0.  1.  0.]
==
3750
[-0.  1.  0.]
==
3767
[-0.  1.  0.]
==
3773
[-0.  1.  0.]
==
3781
[-0.  1.  0.]
==
3796
[-1  0  0]
==
3797
[0 1 0]
==
3805
[-0.  1.  0.]
==
3815
[-0.  1.  0.]
==
3821
[-0.  1.  0.]
==
3829
[-0.  1.  0.]
==
3849
[-0.  1.  0.]
==
3853
[-0.  1.  0.]
==
3866
[-0.  1.  0.]
==
3871
[-0.  1.  0.]
==
3891
[-0.  1.  0.]
==
3925
[-1  0  0]
==
3927
[0 1 0]
==
3935
[-0.  1.  0.]
==
3938
[-0.  1.  0.]
==
3957
[-0.  1.  0.]
==
3963
[-0.  1.  0.]
==
3971
[-0.  1.  0.]
==
3975
[-0.  1.  0.]
==
3993
[0 1 0]
==
3994
[-1  0  0]
==
3997
[-0.  1.  0.]
==
4008
[-0.  1.  0.]
==
4015
[-0.  1.  0.]
==
4019
[-0.  1.  0.]
==
4034
[-0.  1.  0.]
==
4045
[-0.  1.  0.]
==
4058
[-0.  1.  0.]
==
4067
[-0.  1.  0.]
==
4072
[-0.  1.  0.]
==
4090
[-0.  1.  0.]
==
4094
[-0.  1.  0.]
==
4133
[-0.  1.  0.]
==
4146
[-0.  1.  0.]
==
4165
[-0.  1.  0.]
==
4174
[-0.  1.  0.]
==
4183
[-0.  1.  0.]
==
4187
[-1  0  0]
==
4188
[0 1 0]
==
4208
[-0.  1.  0.]
==
4213
[-0.  1.  0.]
==
4218
[-0.  1.  0.]
==
4220
[ 0. -0.  1.]
==
4239
[-0.  1.  0.]
==
4241
[-0.  1.  0.]
==
4250
[-0.  1.  0.]
==
4258
[-0.  1.  0.]
==
4273
[-0.  1.  0.]
==
4275
[-0.  1.  0.]
==
4288
[-0.  1.  0.]
==
4292
[-0.  1.  0.]
==
4297
[-0.  1.  0.]
==
4313
[-0.  1.  0.]
==
4324
[-0.  1.  0.]
==
4337
[-0.  1.  0.]
==
4342
[-1  0  0]
==
4344
[0 1 0]
==
4347
[-0.  1.  0.]
==
4362
[-0.  1.  0.]
==
4363
[ 0. -0.  1.]
==
4370
[-0.  1.  0.]
==
4373
[-0.  1.  0.]
==
4383
[-0.  1.  0.]
==
4389
[-0.  1.  0.]
==
4403
[-0.  1.  0.]
==
4415
[-1  0  0]
==
4419
[0 1 0]
==
4422
[-0.  1.  0.]
==
4433
[-0.  1.  0.]
==
4434
[-0.  1.  0.]
==
4443
[-0.  1.  0.]
==
4454
[-0.  1.  0.]
==
4463
[-0.  1.  0.]
==
4475
[-0.  1.  0.]
==
4483
[0 1 0]
==
4484
[-1  0  0]
==
4489
[-1  0  0]
==
4495
[-1  0  0]
==
4497
[-0.  1.  0.]
==
4511
[-0.  1.  0.]
==
4521
[-0.  1.  0.]
==
4522
[-0.  1.  0.]
==
4536
[-0.  1.  0.]
==
4546
[0 1 0]
==
4547
[-1  0  0]
==
4553
[-1  0  0]
==
4556
[0 1 0]
==
4558
[-0.  1.  0.]
==
4565
[-0.  1.  0.]
==
4572
[-1  0  0]
==
4576
[0 1 0]
==
4579
[0 1 0]
==
4580
[-1  0  0]
==
4584
[-1  0  0]
==
4587
[0 1 0]
==
4600
[-0.  1.  0.]
==
4609
[-0.  1.  0.]
==
4616
[-0.  1.  0.]
==
4623
[-0.  1.  0.]
==
4628
[-0.  1.  0.]
==
4640
[-0.  1.  0.]
==
4647
[-0.  1.  0.]
==
4654
[-0.  1.  0.]
==
4662
[-0.  1.  0.]
==
4676
[0 1 0]
==
4677
[-1  0  0]
==
4680
[-0.  1.  0.]
==
4692
[-0.  1.  0.]
==
4710
[-0.  1.  0.]
==
4717
[-0.  1.  0.]
==
4723
[-0.  1.  0.]
==
4726
[-0.  1.  0.]
==
4748
[-0.  1.  0.]
==
4749
[-0.  1.  0.]
==
4756
[-0.  1.  0.]
==
4765
[-0.  1.  0.]
==
4779
[-1  0  0]
==
4781
[0 1 0]
==
4787
[-0.  1.  0.]
==
4792
[-0.  1.  0.]
==
4802
[-0.  1.  0.]
==
4810
[0. 1. 0.]
==
4811
[0. 1. 0.]
==
4819
[-0.  1.  0.]
==
4827
[0. 1. 0.]
==
4830
[-1  0  0]
==
4832
[0 1 0]
==
4842
[-0.  1.  0.]
==
4849
[0 1 0]
==
4850
[-1  0  0]
==
4855
[-0.  1.  0.]
==
4865
[-1  0  0]
==
4866
[0 1 0]
==
4873
[-0.  1.  0.]
==
4880
[0.01 1.   0.  ]
==
4887
[-0.  1.  0.]
==
4894
[-0.  1.  0.]
==
4906
[-0.  1.  0.]
==
4909
[-1  0  0]
==
4910
[0 1 0]
==
4918
[0 1 0]
==
4922
[0 1 0]
==
4923
[-1  0  0]
==
4926
[0 1 0]
==
4927
[-1  0  0]
==
4945
[-0.  1.  0.]
==
4975
[-0.  1.  0.]
==
4979
[-0.  1.  0.]
==
4986
[0. 1. 0.]
==
4991
[-0.  1.  0.]
==
5001
[-0.  1.  0.]
==
5016
[-0.  1.  0.]
==
5026
[-0.  1.  0.]
==
5027
[-0.  1.  0.]
==
5035
[-1  0  0]
==
5039
[0 1 0]
==
5047
[-1  0  0]
==
5050
[0 1 0]
==
5071
[-0.  1.  0.]
==
5079
[0. 1. 0.]
==
5088
[-0.  1.  0.]
==
5092
[-0.  1.  0.]
==
5096
[0 1 0]
==
5099
[-0.  1.  0.]
==
5105
[0. 1. 0.]
==
5112
[-1  0  0]
==
5115
[0 1 0]
==
5116
[0 1 0]
==
5117
[-1  0  0]
==
5122
[-0.  1.  0.]
==
5135
[-0.  1.  0.]
==
5150
[-0.  1.  0.]
==
5160
[-0.  1.  0.]
==
5166
[-0.  1.  0.]
==
5169
[0 1 0]
==
5176
[-0.  1.  0.]
==
5188
[0. 1. 0.]
==
5193
[0 1 0]
==
5196
[0 1 0]
==
5198
[-1  0  0]
==
5201
[0 1 0]
==
5202
[-0.  1.  0.]
==
5209
[-0.  1.  0.]
==
5213
[-0.  1.  0.]
==
5220
[-0.  1.  0.]
==
5225
[0 1 0]
==
5227
[-0.  1.  0.]
==
5233
[-0.  1.  0.]
==
5245
[-0.  1.  0.]
==
5253
[-0.  1.  0.]
==
5269
[-0.  1.  0.]
==
5274
[0. 1. 0.]
==
5280
[-0.  1.  0.]
==
5281
[-0.  1.  0.]
==
5287
[-0.  1.  0.]
==
5293
[0 1 0]
==
5299
[0 1 0]
==
5311
[-0.  1.  0.]
==
5315
[-0.  1.  0.]
==
5323
[0 1 0]
==
5326
[-0.  1.  0.]
==
5336
[-1  0  0]
==
5337
[0 1 0]
==
5347
[-0.  1.  0.]
==
5356
[0 1 0]
==
5359
[-1  0  0]
==
5360
[0 1 0]
==
5369
[-0.  1.  0.]
==
5373
[0. 1. 0.]
==
5378
[0 1 0]
==
5383
[-0.  1.  0.]
==
5396
[-0.  1.  0.]
==
5408
[-0.  1.  0.]
==
5410
[-0.  1.  0.]
==
5425
[0 1 0]
==
5432
[-0.  1.  0.]
==
5442
[-0.  1.  0.]
==
5456
[0 1 0]
==
5459
[-0.  1.  0.]
==
5468
[-0.  1.  0.]
==
5480
[-0.  1.  0.]
==
5488
[0 1 0]
==
5494
[-0.  1.  0.]
==
5502
[0 1 0]
==
5506
[0 1 0]
==
5517
[-0.  1.  0.]
==
5526
[-1  0  0]
==
5528
[0 1 0]
==
5544
[-0.  1.  0.]
==
5548
[0. 1. 0.]
==
5554
[0 1 0]
==
5558
[0 1 0]
==
5560
[-1  0  0]
==
5570
[0 1 0]
==
5580
[-0.  1.  0.]
==
5586
[-0.  1.  0.]
==
5598
[-0.  1.  0.]
==
5602
[0 1 0]
==
5611
[0 1 0]
==
5617
[-0.  1.  0.]
==
5651
[0 1 0]
==
5658
[-0.  1.  0.]
==
5670
[0 1 0]
==
5671
[-1  0  0]
==
5675
[-0.  1.  0.]
==
5686
[-0.  1.  0.]
==
5696
[-0.  1.  0.]
==
5699
[-0.  1.  0.]
==
5704
[0 1 0]
==
5714
[-0.  1.  0.]
==
5720
[-0.  1.  0.]
==
5729
[-0.  1.  0.]
==
5745
[0. 1. 0.]
==
5756
[-0.  1.  0.]
==
5762
[-0.  1.  0.]
==
5771
[-0.  1.  0.]
==
5780
[-0.  1.  0.]
==
5788
[-0.  1.  0.]
==
5801
[-0.  1.  0.]
==
5807
[-0.  1.  0.]
==
5812
[-1  0  0]
==
5813
[0 1 0]
==
5820
[0 1 0]
==
5835
[-0.  1.  0.]
==
5841
[0 1 0]
==
5843
[0 1 0]
==
5852
[-0.  1.  0.]
==
5858
[-0.  1.  0.]
==
5875
[0 1 0]
==
5876
[-1  0  0]
==
5884
[-0.  1.  0.]
==
5898
[0.01 1.   0.  ]
==
5903
[-0.  1.  0.]
==
5910
[-0.  1.  0.]
==
5915
[0. 1. 0.]
==
5921
[-0.  1.  0.]
==
5932
[-0.  1.  0.]
==
5938
[-0.  1.  0.]
==
5951
[-0.  1.  0.]
==
5966
[-0.  1.  0.]
==
5972
[-0.  1.  0.]
==
5980
[0. 1. 0.]
==
5984
[0 1 0]
==
5985
[-1  0  0]
==
5993
[-0.  1.  0.]
==
6003
[-0.  1.  0.]
==
6010
[-0.  1.  0.]
==
6025
[-0.  1.  0.]
==
6029
[-0.  1.  0.]
==
6049
[-0.  1.  0.]
==
6068
[-0.  1.  0.]
==
6077
[-0.  1.  0.]
==
6084
[-0.  1.  0.]
==
6096
[-0.  1.  0.]
==
6106
[-0.  1.  0.]
==
6114
[-0.  1.  0.]
==
6131
[0 1 0]
==
6133
[-1  0  0]
==
6141
[0 1 0]
==
6143
[-1  0  0]
==
6155
[-0.  1.  0.]
==
6166
[-0.  1.  0.]
==
6173
[-0.  1.  0.]
==
6193
[0 1 0]
==
6200
[-0.  1.  0.]
==
6206
[-0.  1.  0.]
==
6214
[-0.  1.  0.]
==
6232
[-0.  1.  0.]
==
6245
[-0.  1.  0.]
==
6250
[-0.  1.  0.]
==
6264
[0 1 0]
==
6269
[0. 1. 0.]
==
6273
[-0.  1.  0.]
==
6287
[0. 1. 0.]
==
6291
[0 1 0]
==
6292
[-1  0  0]
==
6298
[-0.  1.  0.]
==
6300
[0 1 0]
==
6309
[-0.  1.  0.]
==
6315
[-1  0  0]
==
6319
[0 1 0]
==
6326
[-1  0  0]
==
6331
[0 1 0]
==
6351
[-0.  1.  0.]
==
6356
[0. 1. 0.]
==
6364
[-0.  1.  0.]
==
6366
[0 1 0]
==
6372
[-0.  1.  0.]
==
6380
[-1  0  0]
==
6381
[0 1 0]
==
6387
[0 1 0]
==
6389
[0 1 0]
==
6396
[-0.  1.  0.]
==
6400
[-0.  1.  0.]
==
6406
[0 1 0]
==
6409
[-1  0  0]
==
6419
[0 1 0]
==
6423
[0 1 0]
==
6424
[0 1 0]
==
6427
[-0.  1.  0.]
==
6438
[-0.  1.  0.]
==
6445
[-1  0  0]
==
6446
[0 1 0]
==
6453
[0 1 0]
==
6455
[0 1 0]
==
6477
[-1  0  0]
==
6478
[0 1 0]
==
6482
[0 1 0]
==
6484
[-1  0  0]
==
6485
[0 1 0]
==
6486
[-1  0  0]
==
6505
[-0.  1.  0.]
==
6515
[0. 1. 0.]
==
6521
[0. 1. 0.]
==
6535
[0 1 0]
==
6537
[-0.  1.  0.]
==
6543
[0 1 0]
==
6547
[-1  0  0]
==
6551
[0. 1. 0.]
==
6556
[-1  0  0]
==
6559
[0 1 0]
==
6563
[0. 1. 0.]
==
6568
[-1  0  0]
==
6569
[0 1 0]
==
6572
[0. 1. 0.]
==
6578
[0 1 0]
==
6584
[-0.  1.  0.]
==
6594
[-0.  1.  0.]
==
6598
[-0.  1.  0.]
==
6603
[0 1 0]
==
6639
[0 1 0]
==
6641
[-1  0  0]
==
6649
[0 1 0]
==
6652
[0 1 0]
==
6653
[-1  0  0]
==
6657
[0 1 0]
==
6658
[-1  0  0]
==
6672
[-0.  1.  0.]
==
6676
[0. 1. 0.]
==
6680
[0 1 0]
==
6688
[-0.  1.  0.]
==
6692
[-0.  1.  0.]
==
6706
[-1  0  0]
==
6708
[0 1 0]
==
6715
[0 1 0]
==
6716
[-1  0  0]
==
6726
[-0.  1.  0.]
==
6738
[0 1 0]
==
6743
[-1  0  0]
==
6748
[-0.  1.  0.]
==
6753
[-0.  1.  0.]
==
6764
[-0.  1.  0.]
==
6775
[0 1 0]
==
6777
[-1  0  0]
==
6778
[0 1 0]
==
6791
[0. 1. 0.]
==
6795
[-0.  1.  0.]
==
6802
[-1  0  0]
==
6804
[0 1 0]
==
6814
[0 1 0]
==
6815
[-1  0  0]
==
6821
[-0.  1.  0.]
==
6823
[0. 1. 0.]
==
6837
[0. 1. 0.]
==
6848
[-1  0  0]
==
6850
[0 1 0]
==
6851
[-1  0  0]
==
6852
[0 1 0]
==
6861
[-0.  1.  0.]
==
6872
[-0.  1.  0.]
==
6877
[0. 1. 0.]
==
6881
[-0.  1.  0.]
==
6886
[0 1 0]
==
6896
[0. 1. 0.]
==
6905
[-1  0  0]
==
6906
[0 1 0]
==
6915
[-0.  1.  0.]
==
6918
[0 1 0]
==
6922
[0. 1. 0.]
==
6927
[-0.  1.  0.]
==
6931
[0. 1. 0.]
==
6940
[0 1 0]
==
6945
[0 1 0]
==
6949
[0 1 0]
==
6953
[-1  0  0]
==
6954
[0 1 0]
==
6958
[0. 1. 0.]
==
6968
[-0.  1.  0.]
==
6975
[-0.  1.  0.]
==
6981
[-0.  1.  0.]
==
6985
[-0.  1.  0.]
==
6989
[-1  0  0]
==
6993
[0 1 0]
==
6999
[-0.  1.  0.]
==
7002
[-0.  1.  0.]
==
7007
[0. 1. 0.]
==
7012
[0 1 0]
==
7014
[0 1 0]
==
7017
[-1  0  0]
==
7033
[-1  0  0]
==
7034
[0 1 0]
==
7038
[0 1 0]
==
7041
[-1  0  0]
==
7043
[0. 1. 0.]
==
7061
[-0.  1.  0.]
==
7075
[-0.  1.  0.]
==
7088
[-0.  1.  0.]
==
7089
[-0.  1.  0.]
==
7100
[-0.  1.  0.]
==
7108
[-1  0  0]
==
7109
[0 1 0]
==
7112
[-0.  1.  0.]
==
7119
[-0.  1.  0.]
==
7126
[0 1 0]
==
7135
[0. 1. 0.]
==
7136
[0 1 0]
==
7141
[-0.  1.  0.]
==
7144
[-0.  1.  0.]
==
7150
[-0.  1.  0.]
==
7163
[0. 1. 0.]
==
7168
[-0.  1.  0.]
==
7172
[0 1 0]
==
7174
[-1  0  0]
==
7176
[0 1 0]
==
7177
[-1  0  0]
==
7186
[-0.  1.  0.]
==
7187
[-0.  1.  0.]
==
7191
[0. 1. 0.]
==
7194
[0. 1. 0.]
==
7206
[0. 1. 0.]
==
7209
[0. 1. 0.]
==
7214
[-0.  1.  0.]
==
7221
[-0.  1.  0.]
==
7244
[-0.  1.  0.]
==
7252
[-0.  1.  0.]
==
7258
[-0.  1.  0.]
==
7262
[0 1 0]
==
7267
[-0.  1.  0.]
==
7278
[0. 1. 0.]
==
7285
[-0.  1.  0.]
==
7288
[0 1 0]
==
7292
[-1  0  0]
==
7296
[-0.  1.  0.]
==
7302
[-1  0  0]
==
7304
[0 1 0]
==
7306
[-0.  1.  0.]
==
7314
[-0.  1.  0.]
==
7318
[0 1 0]
==
7320
[-1  0  0]
==
7323
[-0.  1.  0.]
==
7329
[0 1 0]
==
7330
[-1  0  0]
==
7343
[-1  0  0]
==
7345
[0 1 0]
==
7363
[-0.  1.  0.]
==
7374
[0. 1. 0.]
==
7377
[0 1 0]
==
7406
[-0.  1.  0.]
==
7408
[0 1 0]
==
7412
[-0.  1.  0.]
==
7426
[-0.  1.  0.]
==
7435
[0. 1. 0.]
==
7439
[-0.  1.  0.]
==
7446
[-0.  1.  0.]
==
7449
[-0.  1.  0.]
==
7460
[0. 1. 0.]
==
7464
[0 1 0]
==
7466
[-1  0  0]
==
7470
[-1  0  0]
==
7475
[0 1 0]
==
7476
[0. 1. 0.]
==
7483
[0. 1. 0.]
==
7488
[-0.  1.  0.]
==
7491
[0. 1. 0.]
==
7497
[0 1 0]
==
7502
[-0.  1.  0.]
==
7506
[-0.  1.  0.]
==
7519
[-0.  1.  0.]
==
7523
[0. 1. 0.]
==
7526
[-0.  1.  0.]
==
7541
[0. 1. 0.]
==
7546
[0 1 0]
==
7548
[-0.  1.  0.]
==
7558
[0 1 0]
==
7565
[0 1 0]
==
7566
[-1  0  0]
==
7574
[0 1 0]
==
7575
[-1  0  0]
==
7585
[-0.  1.  0.]
==
7598
[-0.  1.  0.]
==
7601
[0 1 0]
==
7605
[-0.  1.  0.]
==
7619
[0 1 0]
==
7620
[-0.  1.  0.]
==
7640
[-0.  1.  0.]
==
7643
[0. 1. 0.]
==
7648
[0 1 0]
==
7652
[0 1 0]
==
7653
[-1  0  0]
==
7659
[-0.  1.  0.]
==
7668
[0 1 0]
==
7673
[-1  0  0]
==
7680
[0. 1. 0.]
==
7685
[-0.  1.  0.]
==
7690
[-1  0  0]
==
7694
[0 1 0]
==
7697
[0 1 0]
==
7702
[-0.  1.  0.]
==
7707
[-0.  1.  0.]
==
7714
[-0.  1.  0.]
==
7715
[-0.  1.  0.]
==
7719
[-0.  1.  0.]
==
7738
[0 1 0]
==
7741
[-0.  1.  0.]
==
7747
[-0.  1.  0.]
==
7754
[-0.  1.  0.]
==
7759
[0. 1. 0.]
==
7769
[0 1 0]
==
7771
[-1  0  0]
==
7772
[-1  0  0]
==
7776
[0 1 0]
==
7778
[0 1 0]
==
7792
[0 1 0]
==
7797
[-1  0  0]
==
7798
[0 1 0]
==
7799
[-1  0  0]
==
7803
[0 1 0]
==
7815
[-0.  1.  0.]
==
7820
[0. 1. 0.]
==
7824
[-0.  1.  0.]
==
7833
[-0.  1.  0.]
==
7836
[-0.  1.  0.]
==
7842
[-0.  1.  0.]
==
7851
[0 1 0]
==
7853
[-1  0  0]
==
7879
[-0.  1.  0.]
==
7899
[-0.  1.  0.]
==
7906
[-1  0  0]
==
7911
[0 1 0]
==
7914
[-0.  1.  0.]
==
7917
[-0.  1.  0.]
==
7920
[-0.  1.  0.]
==
7938
[-0.  1.  0.]
==
7942
[-0.  1.  0.]
==
7950
[0 1 0]
==
7951
[-1  0  0]
==
7955
[0. 1. 0.]
==
7960
[-1  0  0]
==
7962
[0 1 0]
==
7966
[0 1 0]
==
7967
[-1  0  0]
==
7971
[-0.  1.  0.]
==
7977
[-0.  1.  0.]
==
7985
[-0.  1.  0.]
==
7989
[0 1 0]
==
7997
[0. 1. 0.]
==
8000
[-1  0  0]
==
8003
[0 1 0]
==
8004
[-0.  1.  0.]
==
8014
[-0.  1.  0.]
==
8020
[0 1 0]
==
8031
[-1  0  0]
==
8032
[0 1 0]
==
8044
[-1  0  0]
==
8045
[0 1 0]
==
8052
[0. 1. 0.]
==
8056
[-0.  1.  0.]
==
8062
[0 1 0]
==
8064
[-1  0  0]
==
8068
[-1  0  0]
==
8070
[0 1 0]
==
8074
[0. 1. 0.]
==
8075
[0 1 0]
==
8085
[-0.  1.  0.]
==
8086
[0 1 0]
==
8091
[-1  0  0]
==
8103
[0. 1. 0.]
==
8117
[-0.  1.  0.]
==
8123
[-1  0  0]
==
8124
[0 1 0]
==
8144
[-0.  1.  0.]
==
8148
[0 1 0]
==
8150
[0 1 0]
==
8160
[-0.  1.  0.]
==
8163
[0 1 0]
==
8166
[-1  0  0]
==
8171
[-0.  1.  0.]
==
8181
[-0.  1.  0.]
==
8189
[-0.  1.  0.]
==
8194
[0. 1. 0.]
==
8199
[-0.  1.  0.]
==
8209
[-0.  1.  0.]
==
8215
[0. 1. 0.]
==
8220
[0. 1. 0.]
==
8227
[0. 1. 0.]
==
8229
[0 1 0]
==
8235
[0 1 0]
==
8240
[0. 1. 0.]
==
8246
[0. 1. 0.]
==
8250
[0. 1. 0.]
==
8260
[0 1 0]
==
8261
[-1  0  0]
==
8267
[0. 1. 0.]
==
8268
[-0.  0.  1.]
==
8274
[-0.  1.  0.]
==
8285
[-0.  1.  0.]
==
8286
[0 1 0]
==
8293
[0. 1. 0.]
==
8304
[0. 1. 0.]
==
8310
[0. 1. 0.]
==
8319
[-0.  1.  0.]
==
8324
[0. 1. 0.]
==
8327
[-0.  1.  0.]
==
8341
[-0.  1.  0.]
==
8349
[-0.  1.  0.]
==
8354
[0. 1. 0.]
==
8361
[-0.  1.  0.]
==
8366
[-1  0  0]
==
8367
[0 1 0]
==
8371
[0 1 0]
==
8373
[-1  0  0]
==
8374
[0. 1. 0.]
==
8384
[0. 1. 0.]
==
8388
[-0.  1.  0.]
==
8399
[-0.  1.  0.]
==
8401
[-0.  1.  0.]
==
8413
[-0.  1.  0.]
==
8450
[-0.  1.  0.]
==
8456
[0 1 0]
==
8457
[-1  0  0]
==
8467
[0. 1. 0.]
==
8469
[0. 1. 0.]
==
8475
[0. 1. 0.]
==
8477
[-0.  1.  0.]
==
8485
[-0.  1.  0.]
==
8492
[-0.  1.  0.]
==
8496
[-1  0  0]
==
8497
[0 1 0]
==
8508
[-0.  1.  0.]
==
8511
[-0.  1.  0.]
==
8517
[-1  0  0]
==
8522
[0 1 0]
==
8525
[0. 1. 0.]
==
8530
[0 1 0]
==
8532
[-1  0  0]
==
8533
[-0.  1.  0.]
==
8547
[0. 1. 0.]
==
8552
[0. 1. 0.]
==
8557
[-0.  1.  0.]
==
8562
[-0.  1.  0.]
==
8569
[-0.  1.  0.]
==
8576
[-0.  1.  0.]
==
8580
[0. 1. 0.]
==
8583
[-0.  1.  0.]
==
8591
[0 1 0]
==
8592
[-1  0  0]
==
8594
[0 1 0]
==
8600
[0 1 0]
==
8613
[0. 1. 0.]
==
8615
[0. 1. 0.]
==
8619
[0 1 0]
==
8623
[-1  0  0]
==
8630
[0 1 0]
==
8633
[0. 1. 0.]
==
8638
[0 1 0]
==
8642
[-0.  1.  0.]
==
8653
[-0.  1.  0.]
==
8660
[-1  0  0]
==

In [ ]:
asdf = pd.read_pickle('/gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/headers_pkl/13224275/13224275_pt_0.pkl')

AttributeError: 'FileDataset' object has no attribute 'corrections'

In [23]:
diff = list(set(comb['filename'].values) - set(des['filename'].values))

In [26]:
comb[comb.filename.isin(diff)].to_csv('/gpfs/data/mayerhoeferlab/projects/myeloma/process_dicoms_for_mars/tmp.csv')